import './vendor';
import './lib';
import '../components/Header/header';
import '../components/Gallery/gallery';
import '../components/Catalog/catalog';
import '../components/Events/events';
import '../components/Editions/editions';
import '../components/Projects/projects';
import '../components/Contacts/contacts';
